POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2OWY2NzE2MjdlYjhkZjY5ZmNkM2FlOGUiLCJpYXQiOjE3Nzc4NTQ4ODZ9.ncE1VqM4CX-a5Gl9jmb3ETTPfIAo0kX5hvV4vDRcY1M

{
    "content":"Note with auth token",
    "important":true
}